sudo: required
services:
  - docker

before_install:
  - docker build -t orangeball/introcept-exercise -f Dockerfile.dev .

script:
  - docker run -e CI=true orangeball/introcept-exercise npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "introcept-exercise"
  env: 'IntroceptExercise-env'
  bucket_name: "elasticbeanstalk-us-east-1-245456067642"
  bucket_path: "introcept-exercise"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
