sudo: required
services:
  - docker

before_install:
  - docker build -t orangeball/introcept-exercise -f Dockerfile.dev .

script:
  - docker run -e CI=true orangeball/introcept-exercise npm run test -- --coverage
