sudo: required
install: travis_wait mvn install
services:
  - docker

before_install:
  - docker build -t orangeball/introcept-exercise -f Dockerfile.dev .

script:
  - docker run orangeball/introcept-exercise npm run test -- --coverage
